# Generated by Django 4.2 on 2023-04-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='content',
            field=models.TextField(default=[]),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
